language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - SYMFONY_VERSION=^3.4
  - SYMFONY_VERSION=^4.4
  - SYMFONY_VERSION=^5.0

matrix:
  fast_finish: true
  include:
    - php: '7.2'
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_script:
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - COMPOSER_MEMORY_LIMIT=-1 composer update ${COMPOSER_FLAGS} --no-interaction $(if [[ "$(phpenv version-name)" == "8.0snapshot" ]]; then --ignore-platform-req=php; fi)

script:
  - vendor/bin/phpunit --coverage-clover clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover



